news/urls.py
from django.urls import path
from .views import home, articoloDetailView, listaArticoli, index4, queryBase, giornalistaDetailView

app_name = 'news'

urlpatterns = [
    path('',index4,name='index4'),
    path('homewiew', home, name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name = "articolo_detail"),
    path("giornalisata/<int:pk>", giornalistaDetailView, name = "giornalista_detail"),
    path('lista_articoli/<int:pk>',listaArticoli,name="lista_articoli_giornalista"),
    path('lista_articoli',listaArticoli,name="lista_articoli"),
    path('query_base',queryBase,name='query_base')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index_root,name='index_root'),
    path ('prima_app/' ,include("prima_app.urls",namespace="prima_app")),
    path ('seconda_app/' ,include("seconda_app.urls",namespace="seconda_app")),
    path ('prova_pratica_0/' ,include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path ('news/' ,include("news.urls", namespace="news")),
    path ('voti/' ,include("voti.urls", namespace="voti"))

]

news/models.py
from django.db import models


class Giornalista(models.Model):
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)
    anno_di_nascita = models.DateField(blank=True)

    def __str__(self):
        return self.nome + " " + self.cognome
    
    class Meta:
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"

class Articolo(models.Model):
    titolo = models.CharField(max_length=100)
    contenuto = models.TextField()
    giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")
    data=models.DateField(blank=True)
    visualizzazioni=models.IntegerField(default=0,blank=True)

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

news/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Articolo,Giornalista
import datetime

def home(request):
    articoli = Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti": giornalisti}
    print(context)
    return render(request, "news/homepage.html", context)

def articoloDetailView(request, pk):
    articolo= Articolo.objects.get(pk=pk)
    """articolo = get_object_or_404(Articolo, pk=pk)"""
    context = {"articolo":articolo}
    return render(request, "news/articolo_detail.html", context)
   
def giornalistaDetailView(request, pk):
    giornalista= Giornalista.objects.get(pk=pk)
    articoli= Articolo.objects.filter(giornalista=pk)
    context = {"giornalista":giornalista, "articoli":articoli}
    return render(request, "news/giornalista_detail.html", context)
    """"
    a = [] 
    g = []
    for art in Articolo.objects.all():
        a.append(art.titolo)

    for gio in Giornalista.objects.all():
        g.append(gio.nome)
    
    response = str(a) + "<br>" +  str(g)
    print(response)

    return HttpResponse("<h1>" + response + "</h1>")
"""
"""
   a = ""
   g = ""
   for art in Articolo.objects.all():
      a += (art.titolo + "<br>")
   for gio in Giornalista.objects.all():
      g += (gio.nome + "<br>")
   response = "Articoli:<br>" + a + "<br>Giornalisti:<br>" + g

   return HttpResponse("<h1>" + response + "</h1>")
"""

def listaArticoli(request, pk=None):
    trovato = False
    is_vuota = False
    if pk is None:
        articoli = Articolo.objects.all()
    else:
        trovato = True
        articoli = Articolo.objects.filter(giornalista_id=pk)
    if not articoli:
        is_vuota=True
    context = {
        'trovato':trovato,
        'articoli': articoli, 
        'is_vuota':is_vuota
    }
    return render(request, 'news/lista_articoli.html',context)  

def index4(request):
    return render(request, "news/index4.html")

def queryBase(request):
    articoli_cognome = Articolo.objects.filter(giornalista__cognome='Rossi')
    
    numero_totale_articoli=Articolo.objects.count()

    giornalista_1=Giornalista.objects.get(id=3)
    numero_articoli_giornalista_1= Articolo.objects.filter(giornalista=giornalista_1).count()

    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni')

    articoli_senza_visualizzazioni = Articolo.objects.filter(visualizzazioni = 0)

    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()

    giornalisti_data = Giornalista.objects.filter(anno_di_nascita__gt=datetime.date(1980, 1, 1))

    articoli_del_giorno = Articolo.objects.filter(data=datetime.date(2023,1,1))

    articoli_periodo = Articolo.objects.filter(data__range=(datetime.date(2023,1,1), datetime.date(2023,12,31)))

    giornalisti_nati= Giornalista.objects.filter(anno_di_nascita__lt=datetime.date(1980,1,1))
    articoli_giornalisti=Articolo.objects.filter(giornalista__in=giornalisti_nati)

    giornalista_giovane = Giornalista.objects.order_by('anno_di_nascita').first()

    giornalista_anziano = Giornalista.objects.order_by('-anno_di_nascita').first()

    ultimi = Articolo.objects.order_by('-data')[:5]

    articoli_minime_visualizzazioni = Articolo.objects.filter(visualizzazioni__gte=100)

    articoli_parola = Articolo.objects.filter(titolo__icontains='importante')

    articoli_mese_anno = Articolo.objects.filter(data__month=1, data__year=2023)

    giornalisti_con_articoli_popolari = Giornalista.objects.filter(articoli__visualizzazioni__gte=100).distinct()

    data = datetime.date(1990, 1, 1)
    visualizzazioni = 50

    #vengono selezionati gli articoli di un giornalista nato dopo una certa data e con un minimo di visualizzazione
    articoli_con_and = Articolo.objects.filter(giornalista__anno_di_nascita__gt=data, visualizzazioni__gte=visualizzazioni)

    from django.db.models import Q
    
    #vengono selezionati gli articoli dopo una certa data o con un max di visualizzazioni
    articoli_con_or =Articolo.objects.filter(Q(giornalista__anno_di_nascita__gt=data) | Q(visualizzazioni__lte=visualizzazioni))
    #vengono esclusi gli articoli dei giornalisti nati dopo una certa data
    articoli_con_not = Articolo.objects.filter(~Q(giornalista__anno_di_nascita__lt=data))
    #fa o stesso ma con il metodo exclude
    articoli_con_not = Articolo.objects.exclude(giornalista__anno_di_nascita__lt=data)

    context = {
        'articoli_cognome' : articoli_cognome,
        'numero_totale_articoli' : numero_totale_articoli,
        'numero_articoli_giornalista_1' : numero_articoli_giornalista_1,
        'articoli_ordinati' : articoli_ordinati,
        'articoli_senza_visualizzazioni' : articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato' : articolo_piu_visualizzato,
        'giornalisti_data' : giornalisti_data,
        'articoli_del_giorno' : articoli_del_giorno,
        'articoli_periodo' : articoli_periodo,
        'articoli_giornalisti' : articoli_giornalisti,
        'giornalisti_nati':giornalisti_nati,
        'giornalista_giovane' : giornalista_giovane,
        'giornalista_anziano' : giornalista_anziano,
        'ultimi' : ultimi,
        'articoli_minime_visualizzazioni' : articoli_minime_visualizzazioni,
        'articoli_parola' : articoli_parola,
        'articoli_con_and' : articoli_con_and,
        'articoli_con_or' : articoli_con_or,
        'articoli_con_not' : articoli_con_not,
        'articoli_mese_anno' : articoli_mese_anno,
        'giornalisti_con_articoli_popolari' : giornalisti_con_articoli_popolari
    }
    return render(request, 'query.html', context)

news/templates/news/articolo_detail.html
{%extends 'base.html'%}

{%block title%}
    {{articolo.titolo}}
{%endblock title%}

{%block content%}
    <h1>{{articolo.titolo}}</h1>
    <h3>{{articolo.contenuto}}</h3>
    <h5>Autore: {{articolo.titolo}}</h5>
{%endblock content%}

news/templates/news/giornalista_detail.html
{%extends 'base.html'%}

{%block title%}
    {{giornalista.nome}} {{giornalista.cognome}}
{%endblock title%}

{%block content%}
    <h1>Dettagli del giornalista:</h1>
    <h1>{{giornalista.nome}} {{giornalista.cognome}}</h1>
    <h3>Nato il{{giornalista.anno_di_nascita}}</h3>
    <h4>Tutti i suoi articoli e visualizzazioni</h4>
    <ul>
        {%for articolo in articoli%}
            <li>
                <a href={% url 'news:articolo_detail' articolo.id %}>{{articolo.titolo}}</a> - n.{{articolo.visualizzazioni}} 
            </li>    
        {%endfor%}
    </ul>
{%endblock content%}

news/templates/news/homepage.html
{% extends 'base.html' %}
{% block title%}
    Articoli e Giornalisti
{%endblock title%}
{%block content%}
<h4>Benvenuto</h4>
{%endblock content%}

news/templates/news/index4.html
{% extends "base.html"%}

{%block title%} {{block.super}} {%endblock title%} 
{%block content%}
    <ol>
        <li><a href="/">Index root</a></li>
        <li><a href="{% url 'news:homeview'%}">homeview</a></li>
        <li><a href="{% url 'news:lista_articoli'%}">lista articoli</a></li>
        <li><a href="{% url 'news:query_base'%}">query_base</a></li>
    </ol>
{%endblock content%}

news/templates/news/lista_articoli.html
{% extends 'base.html' %}
{% block title%}
    Lista articoli
{%endblock title%}
{%block content%}
{%if not is_vuota%}
    {%if trovato%}:
        <h4>Articoli del giornalista:</h4>
    {%else%}    
        <h4>Tutti gli articoli:</h4>
    {%endif%}
{%else%}
    <h4>Nessun articolo trovato</h4>
{%endif%}
<hr></hr>
    {% for articolo in articoli%}
        <p><strong>Titolo: </strong>
        <a href="/news/articoli/{{ articolo.id}}">{{articolo.titolo}}</a>
        </p>
        <p><strong>Contenuto: </strong>{{articolo.contenuto}}</p>
        <p><strong>Autore: </strong>
            <a href={% url 'news:giornalista_detail' articolo.giornalista.id %}>{{articolo.giornalista}}</a>
        </p>
        <hr>
    {%endfor%}
{%endblock content%}

news/templates/news/query.html
{% extends "base.html"%}

{% block title%}
    {{ block.super }} | Articoli e Giornalisti
{% endblock title%}

{% block content%}

    <h2>Articoli e statistiche</h2>

    <h4>1. Articoli scritti da giornalisti con un certo cognome</h4>
    {% for articolo in articoli_cognome %}
        <p><strong>Id: </strong><a href="articoli/{{ articolo.id }}">{{ articolo.id }}</a></p>
        <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
    {% endfor %}
    <hr>

    <h4>2. Numero totale di articoli</h4>
    <p>{{ numero_totale_articoli }}</p>
    <hr>

    <h4>3. Numero articoli del giornalista con ID = 1</h4>
    <p>{{ numero_articoli_giornalista_1 }}</p>
    <hr>

    <h4>4. Articoli ordinati per visualizzazioni (decrescente)</h4>
    {% for articolo in articoli_ordinati %}
        <p>{{ articolo.titolo }} – {{ articolo.visualizzazioni }} visualizzazioni</p>
    {% endfor %}
    <hr>

    <h4>5. Articoli senza visualizzazioni</h4>
    {% for articolo in articoli_senza_visualizzazioni %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>6. Articolo più visualizzato</h4>
        <p>
            {{ articolo_piu_visualizzato.titolo }}
            ({{ articolo_piu_visualizzato.visualizzazioni }} visualizzazioni)
        </p>
    <hr>

    <h4>7. Giornalisti nati dopo il 1990</h4>
    {% for giornalista in giornalisti_data %}
        <p>{{ giornalista.nome }} {{ giornalista.cognome }} ({{ giornalista.anno_di_nascita }})</p>
    {% endfor %}
    <hr>

    <h4>8. Articoli pubblicati il 01/01/2023</h4>
    {% for articolo in articoli_del_giorno %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>9. Articoli pubblicati nel 2023</h4>
    {% for articolo in articoli_periodo %}
        <p>{{ articolo.titolo }} – {{ articolo.data }}</p>
    {% endfor %}
    <hr>

    <h4>10. Articoli di giornalisti nati prima del 1980</h4>
    {% for articolo in articoli_giornalisti %}
        <p>{{ articolo.titolo }} – {{ articolo.giornalista }}</p>
    {% endfor %}
    <hr>

    <h4>11. Giornalista più giovane</h4>
    <p>{{ giornalista_giovane.nome }} {{ giornalista_giovane.cognome }}</p>
    <hr>

    <h4>12. Giornalista più anziano</h4>
    {% if giornalista_anziano %}
        <p>{{ giornalista_anziano.nome }} {{ giornalista_anziano.cognome }}</p>
    {% endif %}
    <hr>

    <h4>13. Ultimi 5 articoli pubblicati</h4>
    {% for articolo in ultimi %}
        <p>{{ articolo.titolo }} – {{ articolo.data }}</p>
    {% endfor %}
    <hr>

    <h4>14. Articoli con almeno 100 visualizzazioni</h4>
    {% for articolo in articoli_minime_visualizzazioni %}
        <p>{{ articolo.titolo }} ({{ articolo.visualizzazioni }})</p>
    {% endfor %}
    <hr>

    <h4>15. Articoli che contengono la parola "importante" nel titolo</h4>
    {% for articolo in articoli_parola %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}

    <h4>16. Articoli pubblicati in un certo mese di un anno specifico</h4>
    {% for articolo in articoli_mese_anno %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}

    <h4>17. Giornalisti con almeno un articolo con + di 100 visualizzazioni</h4>
    {% for giornalista in giornalisti_con_articoli_popolari %}
        <p>{{ giornalista.nome }} {{ giornalista.cognome }} </p>
    {% endfor %}

    <h4>18. Articoli di un giornalista nato dopo una certa data e con un minimo di visualizzazione</h4>
    {% for articolo in articoli_con_and %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}

    <h4>19. Articoli dopo una certa data o con un max di visualizzazioni</h4>
    {% for articolo in articoli_con_or %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}

    <h4>20. Esclusi gli articoli dei giornalisti nati dopo una certa data</h4>
    {% for articolo in articoli_con_not %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
{% endblock content%}