news/urls.py
from django.urls import path
from .views import home, articoloDetailView, listaArticoli, index4, queryBase, giornalistaDetailView

app_name = 'news'

urlpatterns = [
    path('',index4,name='index4'),
    path('homewiew', home, name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name = "articolo_detail"),
    path("giornalisata/<int:pk>", giornalistaDetailView, name = "giornalista_detail"),
    path('lista_articoli/<int:pk>',listaArticoli,name="lista_articoli_giornalista"),
    path('lista_articoli',listaArticoli,name="lista_articoli"),
    path('query_base',queryBase,name='query_base')
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage, welcome, lista, chi_siamo, variabili, index

app_name="prima_app"
urlpatterns=[
    path('homepage', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista',lista,name='lista'),
    path('chi_siamo',chi_siamo,name='chi_siamo'),
    path('variabili',variabili,name='variabili'),
    path('',index,name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index_root,name='index_root'),
    path ('prima_app/' ,include("prima_app.urls",namespace="prima_app")),
    path ('seconda_app/' ,include("seconda_app.urls",namespace="seconda_app")),
    path ('prova_pratica_0/' ,include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path ('news/' ,include("news.urls", namespace="news")),
    path ('voti/' ,include("voti.urls", namespace="voti"))

]

prova_pratica_0/urls.py
from django.urls import path
from prova_pratica_0.views import index_prova, somma, media

app_name="prova_pratica_0"
urlpatterns=[
    path('index_prova',index_prova,name='index_prova'),
    path('somma',somma,name='somma'),
    path('media',media,name='media')
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if, if_else_elif, es_for, index_2

app_name="seconda_app"
urlpatterns=[
    path('es_if', es_if, name='es_if'),
    path('if_else_elif', if_else_elif, name = 'if_else_elif'),
    path('es_for', es_for, name = 'es_for'),
    path('index_2', index_2, name='index_2')
]

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>{% block title %} Primo progetto {% endblock title %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


      <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Primo progetto</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prima App
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'prima_app:index'%} ">index</a>
          <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%} ">chi siamo</a>
          <a class="dropdown-item" href="{% url 'prima_app:homepage'%} ">homepage</a>
          <a class="dropdown-item" href="{% url 'prima_app:lista'%} ">lista</a>
          <a class="dropdown-item" href="{% url 'prima_app:variabili'%} ">variabili</a>
          <a class="dropdown-item" href="{% url 'prima_app:welcome'%} ">welcome</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Seconda app
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'seconda_app:index_2'%} ">index</a>
          <a class="dropdown-item" href="{% url 'seconda_app:es_if'%} ">es_if</a>
          <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%} ">if else elif</a>
          <a class="dropdown-item" href="{% url 'seconda_app:es_for'%} ">es for</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prova Pratica 0
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'prova_pratica_0:index_prova'%} ">index</a>
          <a class="dropdown-item" href="{% url 'prova_pratica_0:somma'%} ">somma</a>
          <a class="dropdown-item" href="{% url 'prova_pratica_0:media'%} ">media</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          news
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'news:index4'%} ">index</a>
          <a class="dropdown-item" href="{% url 'news:homeview'%} ">homeview</a>
          <a class="dropdown-item" href="{% url 'news:lista_articoli'%} ">lista articoli</a>
          <a class="dropdown-item" href="{% url 'news:query_base'%} ">query</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<div class="container my-4">
    {%block content%}
    {%endblock content%}
    {%block script%}
    {%endblock script%}
</div>

</body>
</html>

templates/index_root.html
{%extends "base.html"%}

{%block  title%} {{block.super}} | index_2 {%endblock title%}

{%block content%}
      <ol>
        <li><a href="/admin">Pannello admin</a></li>
         <li><a href="{% url 'prima_app:index'%} ">Prima App</a></li>
         <li><a href="{% url 'seconda_app:index_2'%} ">Seconda App</a></li>
         <li><a href="{% url 'prova_pratica_0:index_prova'%} ">Prova Pratica 0</a></li>
         <li><a href="{% url 'news:index4' %} ">News</a></li>
        </ol>
{%endblock content%}